/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tech.basic;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SimpleAuthServer classUnderTest = new SimpleAuthServer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
