/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tech.basic;

public class SimpleAuthServer {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SimpleAuthServer().getGreeting());
    }
}
